---
extends: default

rules:
  comments:
    level: error
  comments-indentation:
    level: error
  document-start:
    level: error
  quoted-strings:
    check-keys: true
    quote-type: single
    required: only-when-needed
  truthy:
    level: error
