// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: post_sync.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PostSync_Get_FullMethodName = "/PostSync/Get"
)

// PostSyncClient is the client API for PostSync service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PostSyncClient interface {
	Get(ctx context.Context, in *PostSyncRequest, opts ...grpc.CallOption) (*PostSyncResponse, error)
}

type postSyncClient struct {
	cc grpc.ClientConnInterface
}

func NewPostSyncClient(cc grpc.ClientConnInterface) PostSyncClient {
	return &postSyncClient{cc}
}

func (c *postSyncClient) Get(ctx context.Context, in *PostSyncRequest, opts ...grpc.CallOption) (*PostSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostSyncResponse)
	err := c.cc.Invoke(ctx, PostSync_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostSyncServer is the server API for PostSync service.
// All implementations must embed UnimplementedPostSyncServer
// for forward compatibility.
type PostSyncServer interface {
	Get(context.Context, *PostSyncRequest) (*PostSyncResponse, error)
	mustEmbedUnimplementedPostSyncServer()
}

// UnimplementedPostSyncServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPostSyncServer struct{}

func (UnimplementedPostSyncServer) Get(context.Context, *PostSyncRequest) (*PostSyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedPostSyncServer) mustEmbedUnimplementedPostSyncServer() {}
func (UnimplementedPostSyncServer) testEmbeddedByValue()                  {}

// UnsafePostSyncServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PostSyncServer will
// result in compilation errors.
type UnsafePostSyncServer interface {
	mustEmbedUnimplementedPostSyncServer()
}

func RegisterPostSyncServer(s grpc.ServiceRegistrar, srv PostSyncServer) {
	// If the following call pancis, it indicates UnimplementedPostSyncServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PostSync_ServiceDesc, srv)
}

func _PostSync_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostSyncServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PostSync_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostSyncServer).Get(ctx, req.(*PostSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PostSync_ServiceDesc is the grpc.ServiceDesc for PostSync service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PostSync_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PostSync",
	HandlerType: (*PostSyncServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _PostSync_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post_sync.proto",
}
