// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: post_sync.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostSyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	MaxResults    int32                  `protobuf:"varint,2,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSyncRequest) Reset() {
	*x = PostSyncRequest{}
	mi := &file_post_sync_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSyncRequest) ProtoMessage() {}

func (x *PostSyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_post_sync_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSyncRequest.ProtoReflect.Descriptor instead.
func (*PostSyncRequest) Descriptor() ([]byte, []int) {
	return file_post_sync_proto_rawDescGZIP(), []int{0}
}

func (x *PostSyncRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *PostSyncRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type PostSyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostSyncResponse) Reset() {
	*x = PostSyncResponse{}
	mi := &file_post_sync_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostSyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostSyncResponse) ProtoMessage() {}

func (x *PostSyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_post_sync_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostSyncResponse.ProtoReflect.Descriptor instead.
func (*PostSyncResponse) Descriptor() ([]byte, []int) {
	return file_post_sync_proto_rawDescGZIP(), []int{1}
}

func (x *PostSyncResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

type Post struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Time          *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=time,proto3" json:"time,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	Tripcode      string                 `protobuf:"bytes,4,opt,name=tripcode,proto3" json:"tripcode,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Uuid          string                 `protobuf:"bytes,6,opt,name=uuid,proto3" json:"uuid,omitempty"`
	ParentUuid    string                 `protobuf:"bytes,7,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Post) Reset() {
	*x = Post{}
	mi := &file_post_sync_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Post) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Post) ProtoMessage() {}

func (x *Post) ProtoReflect() protoreflect.Message {
	mi := &file_post_sync_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Post.ProtoReflect.Descriptor instead.
func (*Post) Descriptor() ([]byte, []int) {
	return file_post_sync_proto_rawDescGZIP(), []int{2}
}

func (x *Post) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *Post) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Post) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Post) GetTripcode() string {
	if x != nil {
		return x.Tripcode
	}
	return ""
}

func (x *Post) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Post) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Post) GetParentUuid() string {
	if x != nil {
		return x.ParentUuid
	}
	return ""
}

var File_post_sync_proto protoreflect.FileDescriptor

const file_post_sync_proto_rawDesc = "" +
	"\n" +
	"\x0fpost_sync.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x0fPostSyncRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vmax_results\x18\x02 \x01(\x05R\n" +
	"maxResults\"/\n" +
	"\x10PostSyncResponse\x12\x1b\n" +
	"\x05posts\x18\x01 \x03(\v2\x05.PostR\x05posts\"\xc9\x01\n" +
	"\x04Post\x12.\n" +
	"\x04time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x04time\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12\x1a\n" +
	"\btripcode\x18\x04 \x01(\tR\btripcode\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x12\n" +
	"\x04uuid\x18\x06 \x01(\tR\x04uuid\x12\x1f\n" +
	"\vparent_uuid\x18\a \x01(\tR\n" +
	"parentUuid28\n" +
	"\bPostSync\x12,\n" +
	"\x03Get\x12\x10.PostSyncRequest\x1a\x11.PostSyncResponse\"\x00B-Z+github.com/mmb/tmpbbs/internal/tmpbbs/protob\x06proto3"

var (
	file_post_sync_proto_rawDescOnce sync.Once
	file_post_sync_proto_rawDescData []byte
)

func file_post_sync_proto_rawDescGZIP() []byte {
	file_post_sync_proto_rawDescOnce.Do(func() {
		file_post_sync_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_post_sync_proto_rawDesc), len(file_post_sync_proto_rawDesc)))
	})
	return file_post_sync_proto_rawDescData
}

var file_post_sync_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_post_sync_proto_goTypes = []any{
	(*PostSyncRequest)(nil),       // 0: PostSyncRequest
	(*PostSyncResponse)(nil),      // 1: PostSyncResponse
	(*Post)(nil),                  // 2: Post
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_post_sync_proto_depIdxs = []int32{
	2, // 0: PostSyncResponse.posts:type_name -> Post
	3, // 1: Post.time:type_name -> google.protobuf.Timestamp
	0, // 2: PostSync.Get:input_type -> PostSyncRequest
	1, // 3: PostSync.Get:output_type -> PostSyncResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_post_sync_proto_init() }
func file_post_sync_proto_init() {
	if File_post_sync_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_post_sync_proto_rawDesc), len(file_post_sync_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_post_sync_proto_goTypes,
		DependencyIndexes: file_post_sync_proto_depIdxs,
		MessageInfos:      file_post_sync_proto_msgTypes,
	}.Build()
	File_post_sync_proto = out.File
	file_post_sync_proto_goTypes = nil
	file_post_sync_proto_depIdxs = nil
}
