---
apiVersion: v1
kind: Service
metadata:
  name: tmpbbs-http
spec:
  externalTrafficPolicy: Local
  ports:
    - port: 8080
  selector:
    statefulset.kubernetes.io/pod-name: tmpbbs-0
  type: NodePort
