// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package tmpbbs

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d replies":             0,
	"Author#tripcode-secret": 3,
	"Close":                  8,
	"Insert emoji using shortcode between colons (:mushroom: becomes 🍄).": 5,
	"Markdown is supported.": 4,
	"Reply":                  6,
	"Title":                  2,
	"URL QR Code":            7,
	"page %d":                1,
}

var en_USIndex = []uint32{ // 10 elements
	0x00000000, 0x0000000e, 0x00000019, 0x0000001f,
	0x00000036, 0x0000004d, 0x00000094, 0x0000009a,
	0x000000a6, 0x000000ac,
} // Size: 64 bytes

const en_USData string = "" + // Size: 172 bytes
	"\x02%[1]d replies\x02page %[1]d\x02Title\x02Author#tripcode-secret\x02Ma" +
	"rkdown is supported.\x02Insert emoji using shortcode between colons (:mu" +
	"shroom: becomes 🍄).\x02Reply\x02URL QR Code\x02Close"

	// Total table size 236 bytes (0KiB); checksum: 33CAB334
