// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package tmpbbs

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US":  &dictionary{index: en_USIndex, data: en_USData},
		"es_419": &dictionary{index: es_419Index, data: es_419Data},
		"hi_IN":  &dictionary{index: hi_INIndex, data: hi_INData},
		"zh_CN":  &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%d replies":             0,
	"Author#tripcode-secret": 3,
	"Close":                  8,
	"Insert emoji using shortcode between colons (:mushroom: becomes 🍄).": 5,
	"Markdown is supported.": 4,
	"Reply":                  6,
	"Title":                  2,
	"URL QR Code":            7,
	"page %d":                1,
}

var en_USIndex = []uint32{ // 10 elements
	0x00000000, 0x0000000e, 0x00000019, 0x0000001f,
	0x00000036, 0x0000004d, 0x00000094, 0x0000009a,
	0x000000a6, 0x000000ac,
} // Size: 64 bytes

const en_USData string = "" + // Size: 172 bytes
	"\x02%[1]d replies\x02page %[1]d\x02Title\x02Author#tripcode-secret\x02Ma" +
	"rkdown is supported.\x02Insert emoji using shortcode between colons (:mu" +
	"shroom: becomes 🍄).\x02Reply\x02URL QR Code\x02Close"

var es_419Index = []uint32{ // 10 elements
	0x00000000, 0x00000011, 0x0000001f, 0x00000027,
	0x0000003e, 0x00000052, 0x000000ac, 0x000000b6,
	0x000000cb, 0x000000d2,
} // Size: 64 bytes

const es_419Data string = "" + // Size: 210 bytes
	"\x02%[1]d respuestas\x02página %[1]d\x02Título\x02Autor#tripcode-secreto" +
	"\x02Se admite Markdown.\x02Inserta emojis usando códigos cortos entre do" +
	"s puntos (:mushroom: se convierte en 🍄).\x02Responder\x02Código QR de la" +
	" URL\x02Cerrar"

var hi_INIndex = []uint32{ // 10 elements
	0x00000000, 0x00000013, 0x00000029, 0x0000003c,
	0x0000007e, 0x000000a7, 0x00000141, 0x0000014e,
	0x0000016f, 0x00000186,
} // Size: 64 bytes

const hi_INData string = "" + // Size: 390 bytes
	"\x02%[1]d जवाब\x02पृष्ठ %[1]d\x02शीर्षक\x02लेखक#ट्रिपकोड-गुप्तशब्द\x02Ma" +
	"rkdown समर्थित है।\x02कोलन के बीच शॉर्टकोड डालकर इमोजी जोड़ें (:mushroom" +
	": 🍄 बन जाता है)।\x02जवाब\x02URL क्यूआर कोड\x02बंद करें"

var zh_CNIndex = []uint32{ // 10 elements
	0x00000000, 0x00000010, 0x0000001e, 0x00000025,
	0x00000039, 0x00000053, 0x000000a2, 0x000000a9,
	0x000000b7, 0x000000be,
} // Size: 64 bytes

const zh_CNData string = "" + // Size: 190 bytes
	"\x02%[1]d 条回复\x02第 %[1]d 页\x02标题\x02作者#暗号密钥\x02支持 Markdown 语法。\x02使用冒号包裹" +
	"的短代码插入表情符号(:mushroom: 会变成 🍄)。\x02回复\x02URL 二维码\x02关闭"

	// Total table size 1218 bytes (1KiB); checksum: E0AB3DC3
