---
name: Check
'on':
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: 6 6 * * 6

permissions:
  checks: write
  contents: read
  security-events: write

jobs:
  actionlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: docker://rhysd/actionlint@sha256:6f03470d0152251d7f07f7c4dc019dbe7024c72cd952f839544c7798843efa8f  # yamllint disable rule:line-length
        with:
          args: -color
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Run ESLint
        run: npm install eslint @eslint/js globals && npx eslint
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - uses: golangci/golangci-lint-action@1e7e51e771db61008b38414a730f564565cf7c20  # yamllint disable rule:line-length
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          go-version-file: go.mod
          go-version-input:
          output-format: sarif
          output-file: ${{ github.ref == 'refs/heads/main' && 'govulncheck.sarif' || '' }}
      - uses: github/codeql-action/upload-sarif@v4
        if: github.ref == 'refs/heads/main' && (success() || failure())
        with:
          sarif_file: govulncheck.sarif
  hadolint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: hadolint/hadolint-action@2332a7b74a6de0dda2e2221d575162eba76ba5e5
  htmlhint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
      - name: Run htmlhint
        run: |
          npm install --global htmlhint
          go run tmpbbs.go &
          sleep 3
          htmlhint http://localhost:8080/
          kill $!
  kubeconform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: kustomize
        run: kubectl kustomize kubernetes > kustomized.yaml
      - uses: docker://ghcr.io/yannh/kubeconform@sha256:85dbef6b4b312b99133decc9c6fc9495e9fc5f92293d4ff3b7e1b30f5611823c
        with:
          args: -strict -summary kustomized.yaml
  markdownlint-cli2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@07035fd053f7be764496c0f8d8f9f41f98305101
        with:
          globs: '**/*.md'
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run shellcheck
        run: find . -type f -name "*.sh" -exec shellcheck --format gcc {} +
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
      - name: Run Stylelint
        run: npm install stylelint stylelint-config-standard && npx stylelint --formatter unix '**/*.css'
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: aquasecurity/trivy-action@e368e328979b113139d6f9068e03accaed98a518
        with:
          exit-code: '1'
          scan-type: fs
          format: sarif
          output: ${{ github.ref == 'refs/heads/main' && 'trivy.sarif' || '' }}
      - uses: github/codeql-action/upload-sarif@v4
        if: github.ref == 'refs/heads/main' && (success() || failure())
        with:
          sarif_file: trivy.sarif
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run yamllint
        run: yamllint .
